require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.telescope"
require "user.alpha"
require "user.whichkey"
require "user.cmp"
require "user.lsp"

